### ISSUE TITLE
Click in furnace

### ISSUE THREAD

**Issue by MrJuju0319** [michael1011/BackPacks#18]
sorry i'm french, i have error for use furnace: 

[04:06:48] [Server thread/ERROR]: Could not pass event InventoryClickEvent to BackPacks v2.2.0
org.bukkit.event.EventException
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:298) ~[craftbukkit-1.10.2-R0.1-SNAPSHOT-latest.jar:git-Bukkit-251a5b6]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[craftbukkit-1.10.2-R0.1-SNAPSHOT-latest.jar:git-Bukkit-251a5b6]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [craftbukkit-1.10.2-R0.1-SNAPSHOT-latest.jar:git-Bukkit-251a5b6]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [craftbukkit-1.10.2-R0.1-SNAPSHOT-latest.jar:git-Bukkit-251a5b6]
at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1792) [craftbukkit-1.10.2-R0.1-SNAPSHOT-latest.jar:git-Bukkit-251a5b6]
at net.minecraft.server.v1_10_R1.PacketPlayInWindowClick.a(SourceFile:33) [craftbukkit-1.10.2-R0.1-SNAPSHOT-latest.jar:git-Bukkit-251a5b6]
at net.minecraft.server.v1_10_R1.PacketPlayInWindowClick.a(SourceFile:10) [craftbukkit-1.10.2-R0.1-SNAPSHOT-latest.jar:git-Bukkit-251a5b6]
at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [craftbukkit-1.10.2-R0.1-SNAPSHOT-latest.jar:git-Bukkit-251a5b6]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_111]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_111]
at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [craftbukkit-1.10.2-R0.1-SNAPSHOT-latest.jar:git-Bukkit-251a5b6]
at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:688) [craftbukkit-1.10.2-R0.1-SNAPSHOT-latest.jar:git-Bukkit-251a5b6]
at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:361) [craftbukkit-1.10.2-R0.1-SNAPSHOT-latest.jar:git-Bukkit-251a5b6]
at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:643) [craftbukkit-1.10.2-R0.1-SNAPSHOT-latest.jar:git-Bukkit-251a5b6]
at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:547) [craftbukkit-1.10.2-R0.1-SNAPSHOT-latest.jar:git-Bukkit-251a5b6]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.lang.NoClassDefFoundError: net/md_5/bungee/api/ChatColor
at at.michael1011.backpacks.listeners.InventoryClick.inventoryClick(InventoryClick.java:39) ~[?:?]
at sun.reflect.GeneratedMethodAccessor1608.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_111]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_111]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:296) ~[craftbukkit-1.10.2-R0.1-SNAPSHOT-latest.jar:git-Bukkit-251a5b6]
... 15 more

Can you show this probleme ?

**Comment by michael1011** [comment]
I used the wrong class that doesn't work with Bukkit. You can download a working version [here](https://michael1011.at/jenkins/job/BackPacks/152/artifact/build/libs/BackPacks-2.2.0.jar).

**Comment by MrJuju0319** [comment]
how use a funace backapack ?

**Comment by MrJuju0319** [comment]
Thanks you is good :) 
this plugins is verygood
